### ISSUE TITLE
功能請求

### ISSUE THREAD

**Issue by whes1015** [LiteLDev/LiteXLoader#15]
添加伺服器關閉事件onServerStoped

```

```

#### 版本及相关选项选择
- LiteXLoader: `0.2.1`

**Comment by yqs112358** [comment]
emmm这个其实并非非常合适，因为在停服的时候几乎没有留下给第三方代码执行的时间。而且，如果服务器是由于崩溃结束或者因为点击右上角的×关闭的话，停服事件也几乎不会触发，或者说可以执行代码的时间极短，反而容易丢失数据
目前对数据储存的方案是，每隔一点时间自动保存一次，而不要考虑停服的情况，这样可以在最大程度保留有效数据储存
你可以试着监听一下后台stop命令的执行，用那个代替onServerStopped事件
加了这个事件，反而容易造成潜在的数据丢失风险

**Comment by whes1015** [comment]
> emmm實際上並不是非常合適，因為這個時候幾乎沒有要停在代碼中。而且，如果是因為崩潰或者結束的時候因為點擊時間的×關閉的話，停服也幾乎不會發生觸發，或者可以執行代碼的時間極短，可能會丟失數據
> 保存的數據，每隔一段時間自動保存一次，而不要考慮停服的情況，這樣可以在最大程度上保存數據保存
> 你執行監聽監聽一下後台停止命令，用那個人代替服務器停止事件加劇
> 了事件，可能容易造成潛在的潛在隱患

我做了一個機器人需要再關閉伺服器時藉由WEBHOOK發送訊息

**Comment by yqs112358** [comment]
emm 问题就是，可能不能完全捕获到關閉伺服器的訊息
如果没捕获到的情况，就会出问题

**Comment by yqs112358** [comment]
你理解我的意思了吗

**Comment by whes1015** [comment]
> 你理解我的意思了吗

好的

**Comment by yqs112358** [comment]
你可以用其他方式来实现，比如说心跳机制这些
