### ISSUE TITLE
某些操作会导致 onContainerChangeSlot 检测结果不准确

### ISSUE THREAD

**Issue by xiaoqch** [LiteLDev/LiteXLoader#16]
1，Windows10客户端如果使用右键从容器中取出一半物品，返回结果显示取出所有物品
2，向容器非空的槽堆叠物品，返回结果为取出已有物品
3，拿物品A替换容器中的物品B，返回结果为取出该槽内物品，而无法监听放置的物品

```

```

#### 复现

非一次性拿出槽内所有物品，向容器内堆叠物品，或拿物品A替换容器中物品B

#### 预期的现象

能正确返回改变物品的类型与数量，以及替换容器内物品的时候能正确返回用来替换的物品
#### 问题频率

每次
#### 版本及相关选项选择
- LiteXLoader: `0.2.1`

**Comment by yqs112358** [comment]
这个可能与玩家客户端是如何实现的操作有关
比如说取出一半物品可能是客户端连续执行了先全部取出再放置一半等类似行为
尽力修复，不过可能不太有效

**Comment by xiaoqch** [comment]
我尝试更改了一下代码直接返回传递oldItem和newItem测试，
`        CallEvent(EVENT_TYPES::onContainerChangeSlot, PlayerClass::newPlayer((Player*)pl), BlockClass::newBlock(block, bpos, bs),
            slotNumber, ItemClass::newItem(oldItem), ItemClass::newItem(newItem));`
测试结果显示的是我前面说的三种行为只会触发一次“onContainerChangeSlot”事件，而且oldItem和newItem分别是更改前后的物品类型和数量没问题，这样的话取出一半物品和向容器堆叠物品因为oldItem和newItem类型一样，所以可以直接通过物品数量相减来判断是取出还是放入，但是第三种情况，拿物品A替换容器中的物品B，因为oldItem和newItem类型不一样，没办法通过当前api传递完整信息，应该需要修改api，

**Comment by yqs112358** [comment]
> 我尝试更改了一下代码直接返回传递oldItem和newItem测试，
> `        CallEvent(EVENT_TYPES::onContainerChangeSlot, PlayerClass::newPlayer((Player*)pl), BlockClass::newBlock(block, bpos, bs),
>             slotNumber, ItemClass::newItem(oldItem), ItemClass::newItem(newItem));`
> 测试结果显示的是我前面说的三种行为只会触发一次“onContainerChangeSlot”事件，而且oldItem和newItem分别是更改前后的物品类型和数量没问题，这样的话取出一半物品和向容器堆叠物品因为oldItem和newItem类型一样，所以可以直接通过物品数量相减来判断是取出还是放入，但是第三种情况，拿物品A替换容器中的物品B，因为oldItem和newItem类型不一样，没办法通过当前api传递完整信息，应该需要修改api，

好家伙感谢你的测试
刚刚看到，抱歉
我尝试一下进行修复，感谢您的反馈

**Comment by yqs112358** [comment]
> 我尝试更改了一下代码直接返回传递oldItem和newItem测试，
> `        CallEvent(EVENT_TYPES::onContainerChangeSlot, PlayerClass::newPlayer((Player*)pl), BlockClass::newBlock(block, bpos, bs),
>             slotNumber, ItemClass::newItem(oldItem), ItemClass::newItem(newItem));`
> 测试结果显示的是我前面说的三种行为只会触发一次“onContainerChangeSlot”事件，而且oldItem和newItem分别是更改前后的物品类型和数量没问题，这样的话取出一半物品和向容器堆叠物品因为oldItem和newItem类型一样，所以可以直接通过物品数量相减来判断是取出还是放入，但是第三种情况，拿物品A替换容器中的物品B，因为oldItem和newItem类型不一样，没办法通过当前api传递完整信息，应该需要修改api，

感谢，将修改回调参数
欢迎期待0.3.0版本更新~
