### ISSUE TITLE
使用pl.getAllTags服务端崩溃

### ISSUE THREAD

**Issue by VoryWork** [LiteLDev/LiteXLoader#21]
var taga = pl.getAllTags()

**Comment by yqs112358** [comment]
抱歉，稍等，是不小心先推送了文档，程序本体还没有更新
今天将更新新版本，抱歉给你造成不便

**Comment by yqs112358** [comment]
你可以先暂时通过读取NBT的"Tag"项来达到同样的目的
新版本更新预计今天发布

**Comment by yqs112358** [comment]
预计明天推送新版本修复问题，久等了！

**Comment by yqs112358** [comment]
已修复，更新最新版lxl即可
