### ISSUE TITLE
大量錯誤

### ISSUE THREAD

**Issue by whes1015** [LiteLDev/LiteXLoader#24]
這些程式在更新之前沒問題更新之後一直報錯，並且伺服器會在第一次啟動加載地圖時閃退

[Error] In Plugin: Anti-cheat-whes1015.js
Uncaught ReferenceError: player is not defined
    at http (<anonymous>:43:29)

[INFO] Player connected: Alan123456111, xuid: 2535420800826845
[LiteXLoader.Js][Error] Event Callback Failed!
[Error] In Plugin: ping.js
Uncaught TypeError: Cannot read property 'avgPing' of undefined
    at load (<anonymous>:5:27)

**Comment by Redbeanw44602** [comment]
請貼出程序具體問題代碼。

**Comment by yqs112358** [comment]
请给出相关的代码，谢谢
目前看来是类似于原插件代码的问题

**Comment by whes1015** [comment]
我剛剛確認問題了
好像 pl.name會出錯
但 pl.realName 不會
還有 avgPing 有問題

**Comment by whes1015** [comment]
> 請提供相關的代碼，謝謝
> 目前看來是非原創插件代碼的

我剛確認問題了
pl.name 會出錯
但 pl.realName 不會
還有 avgPing 有問題

**Comment by whes1015** [comment]
> 請貼出程序具體問題代碼。

我剛確認問題了
pl.name 會出錯
但 pl.realName 不會
還有 avgPing 有問題

**Comment by yqs112358** [comment]
？我这里测试正常
代码无问题
![image](https://user-images.githubusercontent.com/37969157/128692321-f22abbf7-d023-4cfb-b2b8-679c55ca33c2.png)
这玩意位于设备信息对象里面，不在玩家对象里面
pl.name测试正常
![image](https://user-images.githubusercontent.com/37969157/128692376-fab61026-a14b-4cec-8ba5-d74d4f103c97.png)

**Comment by whes1015** [comment]
> ？我這裡測試正常
> 代碼無問題 這玩意位置設備信息對象裡面，不在玩家對象裡面 pl.name測試正常
> ![圖像](https://user-images.githubusercontent.com/37969157/128692321-f22abbf7-d023-4cfb-b2b8-679c55ca33c2.png)
> 
> 
> ![圖像](https://user-images.githubusercontent.com/37969157/128692376-fab61026-a14b-4cec-8ba5-d74d4f103c97.png)
我用的 js

**Comment by whes1015** [comment]
> ？我這裡測試正常
> 代碼無問題 這玩意位置設備信息對象裡面，不在玩家對象裡面 pl.name測試正常
> ![圖像](https://user-images.githubusercontent.com/37969157/128692321-f22abbf7-d023-4cfb-b2b8-679c55ca33c2.png)
> 
> 
> ![圖像](https://user-images.githubusercontent.com/37969157/128692376-fab61026-a14b-4cec-8ba5-d74d4f103c97.png)

![image](https://user-images.githubusercontent.com/44525760/128693253-7049ccd4-2887-4d67-b851-740abd18b986.png)

**Comment by yqs112358** [comment]
e，avgPing和packetloss目前仍然是假数据，因为有问题还没有修复
不过pl.name无问题
关于pl.rename客户端暂时没有刷新的问题，这个不好解决，只能等客户端过一段时间自己刷新，之后可能会出相关接口手动刷新

**Comment by whes1015** [comment]
> 即，avgPing和分組丟失目前仍然是假數據，有因為問題還沒有修復
> 不過pl.name無問題
> 關於pl.rename客戶端暫時沒有刷新的問題，這個不好解決，只能等客戶端過一段時間自己刷新，之後可能會出相關接口手動刷新

收到
我該關閉問題嗎?

**Comment by yqs112358** [comment]
ok
感谢你的反馈
你可以关闭问题了，我已经记录了todo list

**Comment by whes1015** [comment]
> 好的，
> 謝謝你的反饋
> 你可以關閉問題了，我已經記錄了待辦事項清單

收到
