### ISSUE TITLE
一些問題

### ISSUE THREAD

**Issue by whes1015** [LiteLDev/LiteXLoader#25]
1.使用 lxl reload 會導致伺服器關閉
2.pos.x會顯示錯誤碼 但數據依然可以取得
3.不知道什麼原因顯示[LiteXLoader.Js][Error] Too Few arguments!錯誤

```

```

#### 版本及相关选项选择
- LiteXLoader: `0.2.1`

**Comment by yqs112358** [comment]
最新版本已经升级到0.4.1了，请尽快升级到最新版本
文档会跟随最新版本LXL

too few arguments是代表API使用错误，参数数量不足，请参考文档站的**重大更改页面**查看API有无不兼容更改，并检查所有的API调用

**Comment by whes1015** [comment]
> 最新版本已經升級到0.4.1了，請盡快升級到最新版本的
> 文檔會最新版本LXL
> 
> 參數太少是代表API使用錯誤，參數數量不足，請參考文檔站的**重大變化**查看API有無變化，並檢查所有API調用

我是使用0.4.1

**Comment by yqs112358** [comment]
emm我这里无法复现你的问题
你可以把发生问题的插件提交一下吗？或者提交引起错误的片段，我来检查一下
谢谢合作

**Comment by whes1015** [comment]
> emm我這裡無法復現你的問題
> 你可以把發生的問題的插件提交一下嗎？或者提交錯誤的截圖，我來檢查一下
> 謝謝合作

使用 lxl reload 會導致服務器關閉

**Comment by whes1015** [comment]
> emm我這裡無法復現你的問題
> 你可以把發生的問題的插件提交一下嗎？或者提交錯誤的截圖，我來檢查一下
> 謝謝合作

補充一下，有玩家在服務器內的時候reload才會關閉，沒有時則能正常reload

**Comment by yqs112358** [comment]
> > emm我這裡無法復現你的問題
> > 你可以把發生的問題的插件提交一下嗎？或者提交錯誤的截圖，我來檢查一下
> > 謝謝合作
> 
> 補充一下，有玩家在服務器內的時候reload才會關閉，沒有時則能正常reload

非常奇怪，我们这里没有遇到任何问题
包括我的那个有大量Hook的行为日志插件，在将近十位玩家在服务器中时reload重新加载没有任何问题

**Comment by yqs112358** [comment]
试试最新版本？现在已经更新到0.5.1，你说的那些问题还存在吗
