### ISSUE TITLE
监听事件回调函数中使用wsc.send()会致使BDS服务端崩溃

### ISSUE THREAD

**Issue by leoweyr** [LiteLDev/LiteXLoader#40]
继issues#39，在那个问题上，经过多次寻源测试发现问题的根本来源。
如图为示例代码：
![image](https://user-images.githubusercontent.com/58080150/131128067-f049e07b-7afb-440a-b446-3ded3b60ba2c.png)
实践证明，wsc.send()确实也把信息发送到了ws服务端，ws服务端那边收到了。但是在发送后，BDS服务端立刻奔溃
按照往时经验，wsc.send()应该是致使BDS服务端陷入死循环阻塞了主线程。看看开发者能不能再lxl底层代码上解决这个问题

**Comment by leoweyr** [comment]
提米大佬发来的在我这测试依旧是listen监听事件回调函数中使用wsc.send()会致使BDS服务端崩溃，如果它那边正常的化，考虑到你跟我说断开客户端会导致BDS崩溃，我怀疑是ws服务端的问题，可能是ws客户端一发信息过来就致使其断开？
这是我服务端的代码（不知道该怎么改才不会使客户端断开连接）：
![image](https://user-images.githubusercontent.com/58080150/131204338-8a8c6119-fd62-48ea-841c-29615b80bed9.png)

如果断开ws客户端连接真会导致BDS崩溃，那么这也是致命的bug，因为客户端时间久了也会自动断开连接，即使能够断开重连，但是在“断开”这一步就直接崩溃了

**Comment by yqs112358** [comment]
最新beta已修复
