### ISSUE TITLE
没搞懂ws.status的枚举但是实验得出调用ws.status属性返回情况

### ISSUE THREAD

**Issue by leoweyr** [LiteLDev/LiteXLoader#42]
## 实验经过
实验操作如图代码：
![TH58O~8E SGS3} C@LGW9MT](https://user-images.githubusercontent.com/58080150/131219106-a1bf6b7e-ad05-44d1-b11b-f29e5255b9cc.jpg)

1. ws服务端开启时
![CRO @K_3J(X%74 6DF6`N3Q](https://user-images.githubusercontent.com/58080150/131219148-476dfd9c-5962-47c2-b250-6f9bec1a392a.jpg)
2. ws服务端关闭时
![)E$SEU_FEV~~2IHFAQRYU P](https://user-images.githubusercontent.com/58080150/131219160-cca61007-295c-4e89-8d3f-7ec351f15f94.png)

## 实验总结
ws服务端开启时ws.status返回0，正在关闭时返回1，已关闭时返回2。猜想也许结合ws.status调用对应数字能够得出如图所示的字符串？
![image](https://user-images.githubusercontent.com/58080150/131219308-c594bed4-bbc4-4aea-8523-6ca8a1fd0a45.png)
 
## 最后
如果lxl开发者觉得有必要的话，可以在ws.status文档那声明一下不同情况ws,status的返回值

**Comment by yqs112358** [comment]
额确实那些给出的是枚举，其实本质就是数字，本来应该是直接和他们做比较的
确实是你说的那种情况
