### ISSUE TITLE
关于lxl模块函数调用主插件报错device or resource busy: device or resource busy

### ISSUE THREAD

**Issue by leoweyr** [LiteLDev/LiteXLoader#44]
lxl.require调用远程函数错误时，主体插件能够正常运行
但是调用远程函数成功后，主体插件报错device or resource busy: device or resource busy

于是我就干脆写简单的代码测试一下，还是一样的问题
![image](https://user-images.githubusercontent.com/58080150/131254593-4e2a842a-c1f4-4970-a7f4-b837777e6f00.png)

**Comment by leoweyr** [comment]
备注：关于文件占用，是否已经打开编辑器都会device or resource busy: device or resource busy
我重启电脑还是一样，硬盘检查那边也没问题

**Comment by yqs112358** [comment]
未知情况，其他人并未出现此问题

**Comment by leoweyr** [comment]
要不你亲自或者邀请其他人在自己的设备用简单的代码测试一下？看看结果。用最新的action版本

**Comment by leoweyr** [comment]
也许是你较新的版本有些代码发生了冲突？

**Comment by leoweyr** [comment]
使用最新beta版本lxl测试结果
![image](https://user-images.githubusercontent.com/58080150/131281496-402017ca-5e57-46d8-be86-90b26dd3356f.png)

**Comment by Redbeanw44602** [comment]
lxl.require("b.js")是什么神必操作

**Comment by xiaoqch** [comment]
此问题已解决，请等待更新
