### ISSUE TITLE
还有file.open()打不开的文件？

### ISSUE THREAD

**Issue by leoweyr** [LiteLDev/LiteXLoader#47]
源代码：
![image](https://user-images.githubusercontent.com/58080150/131460042-63e71fd4-5e37-483f-b4f3-d98094b3202c.png)

报错：
![image](https://user-images.githubusercontent.com/58080150/131460209-660348ea-3ee8-44f4-8e10-2a09bbdfe980.png)

".mesondb"就是一个普通的文本文件只是自定义后缀而已
我不知道为啥打不开？难道lxl文件读写不能自定义文件后缀？
对了，读取文件是可以的
![image](https://user-images.githubusercontent.com/58080150/131460445-0780d850-e3c7-44f5-867e-7086a04581d2.png)

**Comment by leoweyr** [comment]
群友和我的总结经验
![image](https://user-images.githubusercontent.com/58080150/131461921-e84e9802-4c90-4823-885d-997122b3a122.png)

**Comment by leoweyr** [comment]
对了我的那个文件’.mesondb‘是未创建的

**Comment by yqs112358** [comment]
确实如此，马上修复

**Comment by yqs112358** [comment]
最新beta版已修复，请前往github actions更新beta版
给你带来的不便表示抱歉
