### ISSUE TITLE
一个服务端带插件，打开另外一个服务端就崩溃

### ISSUE THREAD

**Issue by leoweyr** [LiteLDev/LiteXLoader#48]
该服务端都是BDS + LiteLoader + LiteXLoader的环境，结论是逐层实验证明，如果不带插件，两个服务端都能打开

**Comment by leoweyr** [comment]
最新实验证明，无论他们带不带插件，同时开一次后，第二次全部关掉，再想同时开的话，一个能开成功，另外一个崩溃

**Comment by leoweyr** [comment]
崩溃时是在另外一个服务端就要准备监听端口时崩溃的

**Comment by leoweyr** [comment]
经过测试，BDS本体会出现偶发性（多次测试就出现一次，还是手比较快的一次）端口为0的情况，不过我觉得跟这个问题没关系，但又感觉可能又丝丝关系

**Comment by leoweyr** [comment]
补充一下上面的comment，那是监听到了端口出现端口而为0，而现在的issue是没到监听到端口那一步，没看到端口数就崩溃

**Comment by leoweyr** [comment]
最新测试显示，只装LiteLoader情况下，会出现两个服务端不能都打开，一个已打开在运行，再打开另外一个会崩溃，崩溃时是在另外一个服务端就要准备监听端口时崩溃的。测试时已设置端口排除端口占用的情况

**Comment by leoweyr** [comment]
已向那边也提交issue
![U 4)3OR8DMAE0QM{W4Y23 K](https://user-images.githubusercontent.com/58080150/131536178-2a7529e8-5816-4c7f-91d9-f529955357a7.png)
那lxl的开发者看看能不能参与解决问题

**Comment by yqs112358** [comment]
![image](https://user-images.githubusercontent.com/37969157/131587899-1204302b-3c5b-4a2b-81cc-64a05458b755.png)
我服同一台机三个BDS+同样插件，毫无问题
检查自己操作哪里不对
