### ISSUE TITLE
Create KVDatabase Error

### ISSUE THREAD

**Issue by VoryWork** [LiteLDev/LiteXLoader#65]
```
> [0m[交易箱子]正在加载数据库
[1m[38;2;239;046;046m[00:40:24 Error][LevelDB] Fail to load KVDB <./plugins/js_data/shop_chest/db>
> [0m[1m[38;2;239;046;046m[00:40:24 Error][LevelDB] NotFound: ./plugins/js_data/shop_chest/db/LOCK: ϵͳ�Ҳ���ָ����·����

> [0m[1m[38;2;239;046;046m[00:40:24 Error][LiteXLoader] Fail to load ./plugins/js_script\shop_chest.js!
> 
[0m[1m[38;2;239;046;046m[00:40:24 Error][LiteXLoader] In Plugin: shop_chest.js
> [0m[1m[38;2;239;046;046m[00:40:24 Error][LiteXLoader] Uncaught Error: can't create class KVDatabase
>     at <anonymous>:11:10


```

**When running this script,it crashed:**
```
log("[交易箱子]正在加载数据库");
var db = new KVDatabase("./plugins/js_data/shop_chest/db");
var to_destory = [];
```

**Comment by Jasonzyt** [comment]
the database is locked, check if there is any bedrock_server.exe is running

**Comment by Jasonzyt** [comment]
umm, a lot of information is garbled, maybe you should check
1. if there is any process running and occupying the database
2. if your database is normal

**Comment by VoryWork** [comment]
It even can't create a new Database,
Here is the error log:
```
[01:21:36 Error][LevelDB] Fail to load KVDB <./plugins/js_data/shop_chest/db>
[01:21:36 Error][LevelDB] NotFound: ./plugins/js_data/shop_chest/db/LOCK: ϵͳ�Ҳ���ָ����·����
[01:21:36 Error][LiteXLoader] Fail to load ./plugins/js_script\shop_chest.js!
>
[01:21:36 Error][LiteXLoader] In Plugin: shop_chest.js
[01:21:36 Error][LiteXLoader] Uncaught Error: can't create class KVDatabase
    at <anonymous>:11:10

```

**Comment by Soirks** [comment]
you should set a folder 

>
log("[交易箱子]正在加载数据库");
var db = new 
KVDatabase("./plugins/js_data/shop_chest/db/");
var to_destory = [];

**Comment by Soirks** [comment]
> ```
> > ���[0m[交易箱子]正在加载数据库
> ���[1m�[38;2;239;046;046m[00:40:24 Error][LevelDB] Fail to load KVDB <./plugins/js_data/shop_chest/db>
> > ���[0m�[1m�[38;2;239;046;046m[00:40:24 Error][LevelDB] NotFound: ./plugins/js_data/shop_chest/db/LOCK: ϵͳ�Ҳ���ָ����·����
> 
> > ���[0m�[1m�[38;2;239;046;046m[00:40:24 Error][LiteXLoader] Fail to load ./plugins/js_script\shop_chest.js!
> > ��
> ���[0m�[1m�[38;2;239;046;046m[00:40:24 Error][LiteXLoader] In Plugin: shop_chest.js
> > ���[0m�[1m�[38;2;239;046;046m[00:40:24 Error][LiteXLoader] Uncaught Error: can't create class KVDatabase
> > ��    at <anonymous>:11:10
> ��
> ��
> ```
> 
> **When running this script,it crashed:**
> 
> ```
> log("[交易箱子]正在加载数据库");
> var db = new KVDatabase("./plugins/js_data/shop_chest/db");
> var to_destory = [];
> ```

![Uploading IMG_20211215_124431.jpg…]()

**Comment by Soirks** [comment]
> ```
> > ���[0m[交易箱子]正在加载数据库
> ���[1m�[38;2;239;046;046m[00:40:24 Error][LevelDB] Fail to load KVDB <./plugins/js_data/shop_chest/db>
> > ���[0m�[1m�[38;2;239;046;046m[00:40:24 Error][LevelDB] NotFound: ./plugins/js_data/shop_chest/db/LOCK: ϵͳ�Ҳ���ָ����·����
> 
> > ���[0m�[1m�[38;2;239;046;046m[00:40:24 Error][LiteXLoader] Fail to load ./plugins/js_script\shop_chest.js!
> > ��
> ���[0m�[1m�[38;2;239;046;046m[00:40:24 Error][LiteXLoader] In Plugin: shop_chest.js
> > ���[0m�[1m�[38;2;239;046;046m[00:40:24 Error][LiteXLoader] Uncaught Error: can't create class KVDatabase
> > ��    at <anonymous>:11:10
> ��
> ��
> ```
> 
> **When running this script,it crashed:**
> 
> ```
> log("[交易箱子]正在加载数据库");
> var db = new KVDatabase("./plugins/js_data/shop_chest/db");
> var to_destory = [];
> ```

![IMG_20211215_124431](https://user-images.githubusercontent.com/69170210/146124902-4d37d962-f605-4d90-9b9a-0781d854d898.jpg)

**Comment by VoryWork** [comment]
> > ```
> > > ���[0m[交易箱子]正在加载数据库
> > ���[1m�[38;2;239;046;046m[00:40:24 Error][LevelDB] Fail to load KVDB <./plugins/js_data/shop_chest/db>
> > > ���[0m�[1m�[38;2;239;046;046m[00:40:24 Error][LevelDB] NotFound: ./plugins/js_data/shop_chest/db/LOCK: ϵͳ�Ҳ���ָ����·����
> > 
> > > ���[0m�[1m�[38;2;239;046;046m[00:40:24 Error][LiteXLoader] Fail to load ./plugins/js_script\shop_chest.js!
> > > ��
> > ���[0m�[1m�[38;2;239;046;046m[00:40:24 Error][LiteXLoader] In Plugin: shop_chest.js
> > > ���[0m�[1m�[38;2;239;046;046m[00:40:24 Error][LiteXLoader] Uncaught Error: can't create class KVDatabase
> > > ��    at <anonymous>:11:10
> > ��
> > ��
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **When running this script,it crashed:**
> > ```
> > log("[交易箱子]正在加载数据库");
> > var db = new KVDatabase("./plugins/js_data/shop_chest/db");
> > var to_destory = [];
> > ```
> 
> ![IMG_20211215_124431](https://user-images.githubusercontent.com/69170210/146124902-4d37d962-f605-4d90-9b9a-0781d854d898.jpg)

当给出的目录不存在时，LXL 将尝试自动逐层创建对应的目录路径

成功打开数据库后，你可以使用下面的接口来进行相关的操作。

**Comment by VoryWork** [comment]
> 当给出的目录不存在时，LXL 将尝试自动逐层创建对应的目录路径
> 
> 成功打开数据库后，你可以使用下面的接口来进行相关的操作。

https://lxl.litebds.com/#/zh_CN/Development/DataAPI/DataBase

**Comment by Soirks** [comment]
> > 当给出的目录不存在时，LXL 将尝试自动逐层创建对应的目录路径
> > 成功打开数据库后，你可以使用下面的接口来进行相关的操作。
> 
> https://lxl.litebds.com/#/zh_CN/Development/DataAPI/DataBase

你传入的是一个文件 并不是目录 你应当传入目录

**Comment by Soirks** [comment]
> > > ```
> > > > ���[0m[交易箱子]正在加载数据库
> > > ���[1m�[38;2;239;046;046m[00:40:24 Error][LevelDB] Fail to load KVDB <./plugins/js_data/shop_chest/db>
> > > > ���[0m�[1m�[38;2;239;046;046m[00:40:24 Error][LevelDB] NotFound: ./plugins/js_data/shop_chest/db/LOCK: ϵͳ�Ҳ���ָ����·����
> > > 
> > > > ���[0m�[1m�[38;2;239;046;046m[00:40:24 Error][LiteXLoader] Fail to load ./plugins/js_script\shop_chest.js!
> > > > ��
> > > ���[0m�[1m�[38;2;239;046;046m[00:40:24 Error][LiteXLoader] In Plugin: shop_chest.js
> > > > ���[0m�[1m�[38;2;239;046;046m[00:40:24 Error][LiteXLoader] Uncaught Error: can't create class KVDatabase
> > > > ��    at <anonymous>:11:10
> > > ��
> > > ��
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > **When running this script,it crashed:**
> > > ```
> > > log("[交易箱子]正在加载数据库");
> > > var db = new KVDatabase("./plugins/js_data/shop_chest/db");
> > > var to_destory = [];
> > > ```
> > 
> > 
> > ![IMG_20211215_124431](https://user-images.githubusercontent.com/69170210/146124902-4d37d962-f605-4d90-9b9a-0781d854d898.jpg)
> 
> 当给出的目录不存在时，LXL 将尝试自动逐层创建对应的目录路径
> 
> 成功打开数据库后，你可以使用下面的接口来进行相关的操作。

![IMG_20211218_011506](https://user-images.githubusercontent.com/69170210/146582657-92d80a4c-bbfa-436f-9adb-8ec74b616945.jpg)
创建的数据库是一个文件夹 里有很多个文件，而不是只有一个db文件

**Comment by Soirks** [comment]
![IMG_20211218_011800](https://user-images.githubusercontent.com/69170210/146582965-2e20b57b-9dfe-4ea0-8e17-ac098ae5c676.jpg)
你应该写成这样

**Comment by yqs112358** [comment]
问题解决了吗？

**Comment by Jasonzyt** [comment]
问题解决了吗

**Comment by jeffcwj** [comment]
same problem and error in lua

> `locationDB = KVDatabase(dataPath .. "UserLocation")`

it‘s an intermittent error, which means it happened this time and next time it won't happen,then it will happen again, like a cycle. and I don't know how to solve it...

These database files are successfully created, they look like this

![)A)@AQ%A S{O8IN}CAFY~NI](https://user-images.githubusercontent.com/36782366/148971211-5cc6049d-dc40-4607-bd5d-012e6cb7d220.png)

error like this
![))A83U4`_SV $8)G$G2TFR](https://user-images.githubusercontent.com/36782366/148971399-ecc3ebfb-a6e6-414a-befd-83bdc3a6f973.png)
