### ISSUE TITLE
Unknown reason Crashed

### ISSUE THREAD

**Issue by VoryWork** [LiteLDev/LiteXLoader#67]
[Crashed!]
-- Unhandled Exception in -> ntdll.dll
-- Exception Code: 0xC0000374
-- Minidump generated in Directory ./logs/Crash

[TrackBack] Function RtlIsZeroMemory at 0x7FF8C112F080  [ntdll.dll]

**Comment by VoryWork** [comment]
More Information:
[00:56:03 Error][LiteLoader] Event Callback Failed!
[00:56:03 Error][LiteLoader] Uncaught Exception Detected!
[00:56:03 Error][LiteLoader] In Event: LiquidFlowEvent
>
[Crashed!]
-- Unhandled Exception in -> ntdll.dll
-- Exception Code: 0xC0000374
-- Minidump generated in Directory ./logs/Crash

[TrackBack] Function RtlIsZeroMemory at 0x7FF8C112F080  [ntdll.dll]
[TrackBack] Function RtlIsZeroMemory at 0x7FF8C112F080  [ntdll.dll]
[TrackBack] Function RtlpNtSetValueKey at 0x7FF8C1137A30  [ntdll.dll]
[TrackBack] Function RtlpNtSetValueKey at 0x7FF8C1137A30  [ntdll.dll]
[TrackBack] Function RtlpNtSetValueKey at 0x7FF8C1137A30  [ntdll.dll]
[TrackBack] Function RtlGetCurrentServiceSessionId at 0x7FF8C1054850  [ntdll.dll]
[TrackBack] Function RtlFreeHeap at 0x7FF8C1054760  [ntdll.dll]
[TrackBack] Function free_base at 0x7FF8BEEAF040  [ucrtbase.dll]
[TrackBack] Function operator delete at 0x7FF653D15B20  [bedrock_server_mod.exe]
[TrackBack] Function OperationNode<int,Pos2d>::`vector deleting destructor' at 0x7FF652C34B20  [bedrock_server_mod.exe]
[TrackBack] Function BlockSource::getChunk at 0x7FF65392D080  [bedrock_server_mod.exe]
[TrackBack] Function BlockSource::areChunksFullyLoaded at 0x7FF6539221D0  [bedrock_server_mod.exe]
[TrackBack] Function CircuitSystem::evaluate at 0x7FF653A07200  [bedrock_server_mod.exe]
[TrackBack] Function Dimension::tickRedstone at 0x7FF653991480  [bedrock_server_mod.exe]
[TrackBack] Function ServerLevel::tick at 0x7FF65307F110  [bedrock_server_mod.exe]
[TrackBack] Function ???????? at 0x????????
[TrackBack] Function Minecraft::update at 0x7FF6534EB5C0  [bedrock_server_mod.exe]
[TrackBack] Function ServerInstance::_update at 0x7FF653058D40  [bedrock_server_mod.exe]
[TrackBack] Function <lambda_58543e61c869eb14b8c48d51d3fe120b>::operator() at 0x7FF653050260  [bedrock_server_mod.exe]
[TrackBack] Function std::thread::_Invoke<std::tuple<<lambda_58543e61c869eb14b8c48d51d3fe120b> >,0> at 0x7FF653038520  [bedrock_server_mod.exe]
[TrackBack] Function configthreadlocale at 0x7FF8BEEC1B20  [ucrtbase.dll]
[TrackBack] Function BaseThreadInitThunk at 0x7FF8BFB07020  [KERNEL32.DLL]
[TrackBack] Function RtlUserThreadStart at 0x7FF8C1082630  [ntdll.dll]

**Comment by yqs112358** [comment]
thanks for your feedback
most of the problems are solved
we are testing all APIs and will release next beta package in a few days, which will be as stable as the previous one
