### ISSUE TITLE
命令方块无法使用

### ISSUE THREAD

**Issue by yanhy2000** [LiteLDev/LiteXLoader#7]
装载lxl后，在未安装其他插件情况下，命令方块编辑指令后无法使用，无任何反应

**Comment by moxicode** [comment]
补图
![Cache_47be2e858c2a5f03](https://user-images.githubusercontent.com/59305689/126875928-28a0cea8-a506-4a22-b5c6-35e2493689d6.jpg)
![Cache_-5de13a2525b2301f](https://user-images.githubusercontent.com/59305689/126875931-bc95f00c-4ef2-4949-8380-e0f58d2854d6.jpg)

**Comment by yqs112358** [comment]
更新新版LiteLoader即可
LiteLoader底层更新了拦截接口
