### ISSUE TITLE
LXL is frizing the server on linux

### ISSUE THREAD

**Issue by HeliosPe** [LiteLDev/LiteXLoader#71]
The server gets frozen on load of LXL on a linux server. I get the message of successfull loading of LXL quoted below.
([20:58:37 Info][LiteLoader] Plugin <LiteXLoader.Js.dll> loaded
[20:58:37 Info][LiteLoader] Plugin <LiteXLoader.Lua.dll> loaded)  

After those, the server does not react to any command. 

PS. OS  is ubuntu 20.04; LL 2.0.3; latest version of LXL.

![image](https://user-images.githubusercontent.com/85097093/147288116-4be88c9f-7ab6-4710-a317-cc5a424f23a9.png)

**Comment by yqs112358** [comment]
ok thanks for your report
i will have a test for it after my exam 😂

**Comment by yqs112358** [comment]
emmm does the newest version of LL and LXL has this problem too?

**Comment by Redbeanw44602** [comment]
Fixed.
