### ISSUE TITLE
MCManager面板能不能安装lxl 没有wine卖家不提供

### ISSUE THREAD

**Issue by jason64123** [LiteLDev/LiteXLoader#74]
![image](https://user-images.githubusercontent.com/81096523/148633811-26dccd5b-f1bd-463d-b836-82045e219006.png)

![image](https://user-images.githubusercontent.com/81096523/148633824-50b1c85d-8477-4d75-8e6b-a79a0d6b8b89.png)

![image](https://user-images.githubusercontent.com/81096523/148633847-c13a1004-ae94-4ae5-bd11-dae321aadf60.png)

**Comment by Redbeanw44602** [comment]
看起来你装的是Linux版BDS，并不支持LL/LXL。

如果没有Wine，应当换用Windows开服或与卖家商议。这里只处理项目的Issue。
