### ISSUE TITLE
方块放置事件无法获得被放置的方块

### ISSUE THREAD

**Issue by ldliuzhen** [LiteLDev/LiteXLoader#77]
编写插件的过程中监听了  "onPlaceBlock" - 玩家放置方块 事件发现，得到的方块ID和Name都是空气方块所对应的值，而破坏方块事件则正常。于是我使用了 BehaviorLog 插件来验证这一问题。发现BehaviorLog插件记录到的方块破坏也是空气方块。

 
![截图](https://user-images.githubusercontent.com/28777444/149134996-5b21c5ce-6d2e-4f65-b6db-32b6a03108f0.jpg)

```

```

#### 复现

1.下载 官方的bedrock-server-1.18.2.03
2.加载LiteLoader-2.0.6
3.加载LiteXLoader-0.5.11
4.使用"onPlaceBlock"监听

#### 问题频率

本地与服务器皆可复现此问题

#### 版本及相关选项选择
- LiteXLoader: `0.5.11` 

#### 补充信息

这是服务器配置文件
[server.properties.zip](https://github.com/LiteLDev/LiteXLoader/files/7854318/server.properties.zip)

**Comment by yqs112358** [comment]
新版已修复，请更新

**Comment by yqs112358** [comment]
谢谢你的反馈~
