### ISSUE TITLE
lxl 指令判断问题

### ISSUE THREAD

**Issue by pa733** [LiteLDev/LiteXLoader#8]
问题描述：在控制台中，输入的lxl热管理二级指令只要包含了热管理指令的关键词，就会触发相应动作。
复现方法：在控制台输入lxl reloadabcabc114514
预期结果：lxl输出：“[Error] Bad Command!”
实际结果：lxl会执行reload操作。
问题频率：每次
日志：[https://paste.ubuntu.com/p/QkPzw9bTn4/](https://paste.ubuntu.com/p/QkPzw9bTn4/)

**Comment by yqs112358** [comment]
已经修复，明天推送新版本

**Comment by yqs112358** [comment]
已修复，更新最新版lxl即可
