### ISSUE TITLE
希望增加进程通信相关API

### ISSUE THREAD

**Issue by leoweyr** [LiteLDev/LiteXLoader#83]
尽管lxl已经支持websocket，但增加进程通信还是有必要的

**Comment by Redbeanw44602** [comment]
已经支持脚本间相互调用了，脚本与dll插件互调yq还在写，不知道你说的进程通信是不是这个？

**Comment by yqs112358** [comment]
由于todo较多，不一定能快速照顾到每一个要求，还请谅解
我们已经加入todo list
另外LXL项目已迁移，与LiteLoader合并。新项目详见：https://github.com/LiteLDev/LiteLoaderBDS
